AllCops:
  TargetRubyVersion: 2.6.1
  TargetRailsVersion: 5.1
  DisplayStyleGuide:
    Enabled: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - ./bin/*
    - ./db/schema.rb
Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    # Initialisers often have big config blocks...
    - config/initializers/**/*
    - config/environments/development.rb
    # RSpec wraps everything in a block
    - spec/**/*
  ExcludedMethods:
    - namespace
    - draw
    - included

# Because we're not on 12" CRT monitors anymore...
Metrics/LineLength:
  Max: 160
  Exclude:
    # Because seeds is/will be short-lived (they say...)
    - db/seeds.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/Documentation:
  # Don't worry about Rails standard classes for top-level docs
  Exclude:
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb
    - spec/**/*

Rails/LexicallyScopedActionFilter:
  # Administrate generated classes will rely on the superclass to define
  # actions, but we still need to before_action some of them.
  Exclude:
    - app/controllers/admin/categories_controller.rb
    - app/controllers/admin/concepts_controller.rb

inherit_gem:
  rubocop-govuk:
    - config/default.yml
