addons:
  postgresql: '10.1'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  # code_climate:
  #     repo_token: <Get from Code Climate>
# after_success:
#   - bundle exec codeclimate-test-reporter

env:
  global:
    - PGPORT=5433
    - POSTGRES_USER=postgres
before_script:
  - psql -c 'create database npd-find-and-explore;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.6.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec