version: '3'

volumes:
  postgres-data:
    driver: local

services:
  # Our PostgreSQL service:
  postgres:
    image: postgres:10.1
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env.development

  postgres_test:
    image: postgres:10.1
    ports:
      - 5433:5432
    env_file: .env.development

  # This container will run the rails web server:
  web:
    build: .
    env_file: .env.development
    environment:
      - WEBPACK_DEV_HOST=webpacker
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    ports:
      - "3000:3000"
    links:
      - postgres
      - postgres_test
