version: '3'

services:
  web:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=development:test
        - RAILS_ENV=production
      environment:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
