version: '3'

volumes:
  postgres-data:
    driver: local

services:
  # Our PostgreSQL service:
  postgres:
    image: postgres:10.1
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env.development

  postgres_test:
    image: postgres:10.1
    ports:
      - 5433:5432
    env_file: .env.development

  # This container will run the rails web server:
  web:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=
        - RAILS_ENV=development
    env_file: .env.development
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_TEST_HOST=postgres_test
      - POSTGRES_TEST_PORT=5432
      - WEBPACK_DEV_HOST=webpacker
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    volumes:
      .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - postgres_test
