version: '3'

volumes:
  postgres-data:
    driver: local

services:
  # Our PostgreSQL service:
  postgres:
    image: postgres:10.1
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  postgres_test:
    image: postgres:10.1
    ports:
      - 5433:5432
    env_file: .env

  # This container will run the rails web server:
  web:
    build: .
    env_file: .env
    environment:
      - RACK_ENV=${RAILS_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - NODE_ENV=${RAILS_ENV}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - POSTGRES_TEST_HOST=postgres_test
      - POSTGRES_TEST_PORT=5432
      - WEBPACK_DEV_HOST=webpacker
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    ports:
      - "3000:3000"
    links:
      - postgres
      - postgres_test
